language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: s4nchez-start
  api_key:
    secure: hzvnZWbGQdsaHVkOFp77RxqVFvirsifGflPiyru2A6jSEyAzqBP7sSa3LAhudgt8THF2eNXA/MX8iJkQs1w/5/DHP0iD05ULfeZYOusCyL2JgYIzYQMKui+bb3vReW0QfZhTzrXDWMJdVRhmd60mQzcey2DcudYs5wvjttrsvMsZFn0pIXYmKC/E2PTGvdGmzkszYj8oreYWvwoA8xi4elyhZzx2XlrH9BUp3Oko0/iCdXkZSp91k0S4xqLQK3rQVHyUBEEXBeNbiQIWXgKhN7NJssp1EOTizMk5M769S0S7r8dPFuVSfKyZKyMiIVzrShqOAWchX1/1UTiYYFaL3qXD2u9mKFZsOjkLKCQlS/PT/nyMsWRhfEEn20zR7yiLv8b1Ujlq5WWLBPp8fm4RCTJ6v038ZspPDxUGzviURMKqU8MuclO8nGbarvNKlIxQOxvLGL6IY8OjQUEvzMaLtm8JA9I1cw6/bg1vjLpiuS3GjcIJu7DZ8NiB2Ry/N85dJfTEX9A0msrJEvwkTBQwz9rdXrcdEF3U3Ew9b+CfGj/+1vUToLQWHsLLT8UYq3ZeOQJ91CmBIaoOLeLUxDZ32Dx+WWitClizpPXt58MgQ5ou/z/ExYnTLlCc5tPNzJ9e8O/fWAkTC8bBHY98cicYPmf/Gy9OYHVIyylLkMcpluQ=
